repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0 # ← package.json に記載のバージョンに合わせる
    hooks:
      - id: eslint
        verbose: true
        additional_dependencies:
          - eslint@^8.50.0
          - eslint-config-prettier@^9.0.0
          - eslint-import-resolver-typescript@^3.6.1
          - eslint-plugin-import@^2.28.1
          - eslint-plugin-jest@^27.4.0
          - eslint-plugin-no-relative-import-paths@^1.5.2
          - eslint-plugin-prettier@^5.0.0
          - eslint-plugin-unused-imports@^3.0.0
        args: ['--ext', '.ts', '--max-warnings', '0']
        files: ^.*/
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3 # ← package.json に記載のバージョンに合わせる
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@^3.0.3
